# icons: Nerd Fonts v3 Material Design Icons (outline)
tmux:
  symbols:
    branch: '󰘬 '  # U+F062C md-source_branch
    hashprefix: '󰜘 '  # U+F0718 md-source_commit
    ahead: '󰧇 '  # U+F09C7 md-arrow_up_bold_outline
    behind: '󰦿 '  # U+F09BF md-arrow_down_bold_outline
    staged: '󰄵 '  # U+F0135 md-checkbox_marked_outline
    conflict: '󰀪 '  # U+F002A md-alert_outline
    modified: '󰲶 '  # U+F0CB6 md-pencil_outline
    untracked: '󱀶 '  # U+F1036 md-file_question_outline
    stashed: '󱈎 '  # U+F120E md-archive_outline
    clean: '󰗡 '  # U+F05E1 md-check_circle_outline
    insertions: '󰜄 '  # U+F0704 md-plus_box_outline
    deletions: '󰛲 '  # U+F06F2 md-minus_box_outline
  styles:
    state: '#[fg=red]'
    branch: '#[fg=default]'
    remote: '#[fg=default]'
    staged: '#[fg=green]'
    conflict: '#[fg=red,bold]'
    modified: '#[fg=yellow]'
    untracked: '#[fg=magenta]'
    stashed: '#[fg=cyan]'
    clean: '#[fg=green]'
  layout:
  - remote-branch
  - stats
  - divergence
  - flags
