# ==========================================================
# lang
# ==========================================================
[[plugins]]
repo = 'osyo-manga/vim-precious'
on_ft = 'toml'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'ruanyl/coverage.vim'
on_ft = ['typescript', 'typescriptreact','vue']
hook_add = '''
let g:coverage_json_report_path = 'coverage/coverage-final.json'
let g:coverage_show_covered = 0
let g:coverage_sign_covered = 'o'
let g:coverage_show_uncovered = 1
let g:coverage_sign_uncovered = 'x'
let g:coverage_sign_column_always = 0
'''

[[plugins]]
repo = 'yardnsm/vim-import-cost'
build = 'npm install'
on_ft = ['typescript', 'typescriptreact', 'vue']
hook_add = '''
let g:import_cost_always_open_split = 0
if has('nvim')
  let g:import_cost_split_pos = 'right'
  augroup import_cost_auto_run
    autocmd!
    autocmd InsertLeave *.js,*.jsx,*.ts,*.tsx ImportCost
  augroup END
endif
'''

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['vue', 'html']

[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'

[[plugins]]
repo = 'peitalin/vim-jsx-typescript'
on_ft = 'typescriptreact'

[[plugins]]
repo = 'mattn/vim-goimports'

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'

# ==========================================================
# fileformat
# ==========================================================

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
