# ==========================================================
# lang
# ==========================================================
[[plugins]]
repo = 'osyo-manga/vim-precious'
on_ft = 'toml'

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'ruanyl/coverage.vim'
on_ft = ['typescript', 'typescriptreact','vue']
hook_add = '''
let g:coverage_json_report_path = 'coverage/coverage-final.json'
let g:coverage_show_covered = 0
let g:coverage_sign_covered = 'o'
let g:coverage_show_uncovered = 1
let g:coverage_sign_uncovered = 'x'
let g:coverage_sign_column_always = 0
'''

[[plugins]]
repo = 'yardnsm/vim-import-cost'
build = 'npm install'
on_ft = ['typescript', 'typescriptreact', 'vue']
hook_add = '''
let g:import_cost_always_open_split = 0
if has('nvim')
  let g:import_cost_split_pos = 'right'
endif
augroup import_cost_auto_run
  autocmd!
  autocmd InsertLeave *.js,*.jsx,*.ts,*.tsx ImportCost
augroup END
'''

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['vue', 'html']

[[plugins]]
repo = 'posva/vim-vue'
on_ft = 'vue'

# [[plugins]]
# repo = "fatih/vim-go"
# on_ft = 'go'
# hook_add = '''
# let g:go_fmt_command = "goimports"
# let g:go_metalinter_autosave = 1
# let g:go_metalinter_command='golangci-lint'
#
# " keymap
# au FileType go nmap <leader>s <Plug>(go-def-split)
# au FileType go nmap <leader>v <Plug>(go-def-vertical)
# au FileType go nmap <leader>3 <Plug>(go-coverage-toggle)
# au FileType go nmap <leader>4 <Plug>(go-test)
# au FileType go nmap <leader>5 <Plug>(go-test-func)
# '''

[[plugins]]
repo = 'mattn/vim-goimports'

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'


# [[plugins]]
# repo = 'prettier/vim-prettier'
# on_ft = ['javascript', 'typescript', 'css', 'less', 'scss', 'json', 'graphql', 'markdown', 'vue', 'yaml', 'html']
# hook_add = '''
# augroup pretteir
#   autocmd!
#   autocmd BufWritePre *.js,*.ts,*.json,*.vue,*.html PrettierAsync
# augroup END
#
# " keymap
# nnoremap <Leader>fp :<C-u>PrettierAsync<CR>
# '''

# ==========================================================
# fileformat
# ==========================================================

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
