# ==========================================================
# lang
# ==========================================================

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'

[[plugins]]
repo = "posva/vim-vue"
on_ft = ["vue"]

# ==========================================================
# fileformat
# ==========================================================

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
