[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
if = "has('nvim')"
on_i = 1
hook_source = '''
source ~/.config/nvim/plugins/deoplete.vim
'''

# ==========================================================
# lang
# ==========================================================

[[plugins]]
repo = 'hynek/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'leafgarland/typescript-vim'
on_ft = 'typescript'


# ==========================================================
# fileformat
# ==========================================================

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = 'toml'
