display:
  active:
    tab_number: true
    process: true
    process_full: false
    directory: true
    git: true
    environment:
      - icon: '󱇶'
        variable: CLOUDSDK_ACTIVE_CONFIG_NAME
      - icon: '⎈'
        variable: KUBECONFIG_NAME
  inactive:
    tab_number: true
    process: true
    process_full: false
    directory: false
    git: false
    environment: []
