display:
  active:
    items:
     - tab_number
     - process
     - directory
     - environment
     - git
    environment:
      - icon: '󱇶'
        variable: CLOUDSDK_ACTIVE_CONFIG_NAME
      - icon: '⎈'
        variable: KUBECONFIG_NAME
  inactive:
    items:
     - tab_number
     - process
    environment: []
