onboarding = false

[ui]
confirm_close = true
prompt_new_tab_name = false
show_agent_labels_on_pane_borders = true
agent_panel_scope = "all"
agent_panel_sort = "spaces"

[ui.toast]
delivery = "herdr"

[theme]
name = "terminal"

[worktrees]
directory = "~/.wt"

[keys]
settings = ""
reload_config = "prefix+ctrl+r"
goto = "prefix+'"

prefix = "ctrl+t"

split_vertical = ["prefix+v", "prefix+|"]
split_horizontal = ["prefix+s", "prefix+minus"]
focus_pane_left = "alt+left"
focus_pane_down = "alt+down"
focus_pane_up = "alt+up"
focus_pane_right = "alt+right"

new_tab = "prefix+c"
previous_tab = ["prefix+p", "alt+h"]
next_tab = ["prefix+n", "alt+l"]
close_tab = ["prefix+shift+x", "prefix+k"]

new_worktree = ["prefix+shift+g", "alt+c"]
open_worktree = ["prefix+shift+o", "alt+o"]
new_workspace = ["prefix+shift+n", "alt+shift+c"]
previous_workspace = ["prefix+shift+left", "alt+k"]
next_workspace = ["prefix+shift+right", "alt+j"]
